[package]
name = "ash-gltf"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
ash = "0.38.0"
ash-window = "0.13.0"
bytemuck = "1.20.0"
cgmath = "0.18.0"
egui = "0.29.1"
gltf = "1.4.1"
image = "0.25.5"
vk-mem = "0.4.0"
winit = "0.29.11"
